#!/bin/bash

# Create Production PR Script
# This script creates a PR from dev to prod for production deployment

echo "🚀 Creating Production PR..."
echo "============================"

# Check if we're in a git repository
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo "❌ Error: Not in a git repository"
    exit 1
fi

# Get current branch
current_branch=$(git rev-parse --abbrev-ref HEAD)
echo "Current branch: $current_branch"

# Check if we're on dev branch
if [ "$current_branch" != "dev" ]; then
    echo "❌ Error: You must be on the 'dev' branch to create a PR to prod"
    echo "   Current branch: $current_branch"
    echo "   Please run: git checkout dev"
    exit 1
fi

# Check if there are uncommitted changes
if ! git diff-index --quiet HEAD --; then
    echo "❌ Error: You have uncommitted changes"
    echo "   Please commit or stash your changes first"
    exit 1
fi

# Check if dev is ahead of prod
dev_commit=$(git rev-parse dev)
prod_commit=$(git rev-parse origin/prod 2>/dev/null || echo "none")

if [ "$dev_commit" = "$prod_commit" ]; then
    echo "❌ Error: Dev and prod branches are at the same commit"
    echo "   No changes to deploy to production"
    exit 1
fi

echo ""
echo "✅ Ready to create PR from dev to prod"
echo ""
echo "📋 Steps:"
echo "1. Push dev branch (if not already pushed)"
echo "2. Create PR on GitHub"
echo "3. Review and merge the PR"
echo ""

# Check if dev is pushed
if git rev-list HEAD..origin/dev --count > /dev/null 2>&1; then
    echo "🔄 Dev branch needs to be pushed first..."
    echo "   git push origin dev"
    echo ""
    read -p "Push dev branch now? (y/n): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        git push origin dev
        if [ $? -ne 0 ]; then
            echo "❌ Failed to push dev branch"
            exit 1
        fi
        echo "✅ Dev branch pushed successfully"
    else
        echo "❌ Please push dev branch manually first"
        exit 1
    fi
fi

echo ""
echo "🌐 Create PR on GitHub:"
echo "   https://github.com/darbyje/genesys_terrafrom_advanced_session/compare/prod...dev"
echo ""
echo "📋 PR Details:"
echo "   Title: 🚀 Production Deployment - Terraform Changes"
echo "   Base: prod"
echo "   Compare: dev"
echo ""
echo "📝 PR Description:"
echo "   ## Production Terraform Deployment"
echo "   "
echo "   This PR contains Terraform changes for the production environment."
echo "   "
echo "   ### Changes Summary"
echo "   - Automated deployment from dev branch"
echo "   - Terraform plan will be generated by CI/CD"
echo "   "
echo "   ### Required Approvals"
echo "   - [ ] Infrastructure Team Approval"
echo "   - [ ] Security Review"
echo "   - [ ] Change Management Approval"
echo "   "
echo "   ### Deployment Instructions"
echo "   1. Review the Terraform plan in the PR comments"
echo "   2. Ensure all changes are expected and approved"
echo "   3. Merge this PR to deploy to production"
echo "   "
echo "   **⚠️ Warning: This will deploy changes to the production environment**"
echo ""
echo "🎯 What happens when you merge:"
echo "   ✅ GitHub Actions will run Terraform plan"
echo "   ✅ Plan will be posted as a comment on the PR"
echo "   ✅ When PR is merged, Terraform apply will run"
echo "   ✅ Changes will be deployed to production"
echo ""
echo "🔗 Quick Links:"
echo "   - GitHub PR: https://github.com/darbyje/genesys_terrafrom_advanced_session/compare/prod...dev"
echo "   - Actions: https://github.com/darbyje/genesys_terrafrom_advanced_session/actions"
echo "   - Pull Requests: https://github.com/darbyje/genesys_terrafrom_advanced_session/pulls" 